package tn.esprit.tic.se.spr01.Chat.messageContent;

public enum MessageType {
    TEXT,
    NOTIFICATION_CREATE_ROOM,
    NOTIFICATION_ADD_MEMBER,
    NOTIFICATION_REMOVE_MEMBER,
    NOTIFICATION_LEAVE_ROOM,
    NOTIFICATION_MAKE_ADMIN,
    NOTIFICATION_REMOVE_ADMIN,
    NOTIFICATION_CHANGE_NAME
}
